name: Run Tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Set up Docker Buildx
      if: matrix.os == 'macos-latest'
      uses: docker/setup-buildx-action@v2
  
    - name: Set up Docker on Windows
      if: matrix.os == 'windows-latest'
      run: |
        choco install docker-desktop --confirm
        Start-Service Docker
      shell: powershell

    - name: Pull Docker image on Windows
      if: matrix.os == 'windows-latest'
      run: docker pull python:3.10
      shell: powershell

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -e .[dev]

    - name: Format check
      run: ruff format .

    - name: Type check
      run: pyright

    - name: Run tests
      run: pytest
